# https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/
#
# > .chezmoiexternal.$FORMAT is interpreted as a template.
# > This allows different externals to be included on different machines.

[".vim/pack/chezmoi/opt/minpac"]
type = "archive"
exact = true
include = ["*/autoload/**", "*/doc/**", "*/plugin/**"]
refreshPeriod = "24h"
stripComponents = 1
url = "https://github.com/k-takata/minpac/archive/refs/heads/master.zip"

[".vim/colors/zenesque.vim"]
type = "file"
url = "https://raw.githubusercontent.com/vim-scripts/zenesque.vim/master/colors/zenesque.vim"

[".local/share/dict/"]
type = "archive"
url = "https://sourceforge.net/projects/wordlist/files/speller/2020.12.07/wordlist-en_US-2020.12.07.zip/download"
include = ["en_US.txt"]

[".config/helix/themes"]
type = "archive"
refreshPeriod = "168h" # 1-week
extract = true
stripComponents = 3
include = ["*/themes/default/*.toml"]
url = "https://github.com/catppuccin/helix/archive/refs/heads/main.zip"

{{ if eq .chezmoi.os "darwin" }}

[".config/kitty/themes"]
type = "archive"
refreshPeriod = "168h" # 1-week
extract = true
stripComponents = 2
include = ["*/themes/*.conf"]
url = "https://github.com/catppuccin/kitty/archive/refs/heads/main.zip"

["Library/Developer/Xcode/UserData/FontAndColorThemes"]
type = "archive"
refreshPeriod = "168h" # 1-week
extract = true
stripComponents = 2
include = ["*/dist/*.xccolortheme"]
url = "https://github.com/catppuccin/xcode/archive/refs/heads/main.zip"

{{ end }}

{{ if eq .chezmoi.os "windows" }}

["Documents/PowerShell/Modules/Catppuccin"]
type = "archive"
refreshPeriod = "168h" # 1-week
extract = true
stripComponents = 1
include = ["*/en-US/**", "*/*.ps*"]
url = "https://github.com/catppuccin/powershell/archive/refs/heads/main.zip"

[".local/bin/"]
type = "archive"
refreshPeriod = "168h" # 1-week
stripComponents = 0
include = ["eza.exe"]
url = "https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-pc-windows-gnu.zip"

["AppData/Local/imhex/themes/catppuccin-frappe.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://github.com/catppuccin/imhex/releases/latest/download/catppuccin-frappe.json"
["AppData/Local/imhex/themes/catppuccin-latte.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://github.com/catppuccin/imhex/releases/latest/download/catppuccin-latte.json"
["AppData/Local/imhex/themes/catppuccin-macchiato.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://github.com/catppuccin/imhex/releases/latest/download/catppuccin-macchiato.json"
["AppData/Local/imhex/themes/catppuccin-mocha.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://github.com/catppuccin/imhex/releases/latest/download/catppuccin-mocha.json"

{{ else }} # Non-Windows

[".config/fish"]
type = "archive"
refreshPeriod = "168h" # 1-week
extract = true
stripComponents = 1
include = ["*/completions/*.fish", "*/functions/*.fish"]
url = "https://github.com/jorgebucaran/fisher/archive/refs/heads/main.zip"

[".config/kak/bundle/kak-bundle"]
type = "archive"
refreshPeriod = "168h" # 1-week
extract = true
stripComponents = 1
include = ["*/README.md", "*/rc/**"]
url = "https://github.com/jdugan6240/kak-bundle/archive/refs/heads/master.zip"

{{ end }}
