# https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/
#
# > .chezmoiexternal.$FORMAT is interpreted as a template.
# > This allows different externals to be included on different machines.

[".vim/pack/chezmoi/opt/minpac"]
type = "git-repo"
refreshPeriod = "24h"
url = "https://github.com/k-takata/minpac.git"

[".vim/colors/zenesque.vim"]
type = "file"
url = "https://raw.githubusercontent.com/vim-scripts/zenesque.vim/master/colors/zenesque.vim"

[".local/share/dict/words"]
type = "archive-file"
url = "https://sourceforge.net/projects/wordlist/files/speller/2020.12.07/wordlist-en_US-2020.12.07.zip/download"
path = "en_US.txt"

[".config/helix/themes/catppuccin_frappe.toml"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://raw.githubusercontent.com/catppuccin/helix/main/themes/default/catppuccin_frappe.toml"

[".config/helix/themes/catppuccin_latte.toml"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://raw.githubusercontent.com/catppuccin/helix/main/themes/default/catppuccin_latte.toml"

[".config/helix/themes/catppuccin_macchiato.toml"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://raw.githubusercontent.com/catppuccin/helix/main/themes/default/catppuccin_macchiato.toml"

[".config/helix/themes/catppuccin_mocha.toml"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://raw.githubusercontent.com/catppuccin/helix/main/themes/default/catppuccin_mocha.toml"

[".config/gitui/themes"]
type = "archive"
refreshPeriod = "168h" # 1-week
stripComponents = 2
include = ["*/theme/*.ron"]
url = "https://github.com/catppuccin/gitui/archive/refs/heads/main.zip"

[".config/lazygit"]
type = "archive"
refreshPeriod = "168h" # 1-week
stripComponents = 1
include = ["*/themes/**", "*/themes-mergable/**"]
url = "https://github.com/catppuccin/lazygit/archive/refs/heads/main.zip"

[".config/nushell/themes/catppuccin-mocha.nu"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://raw.githubusercontent.com/nushell/nu_scripts/main/themes/nu-themes/catppuccin-mocha.nu"

[".config/bottom/default_config.toml"]
type = "file"
refreshPeriod = "168h" # 1-wee
url = "https://raw.githubusercontent.com/ClementTsang/bottom/master/sample_configs/default_config.toml"

[".config/bottom/themes/frappe.toml"]
type = "file"
refreshPeriod = "168h" # 1-wee
url = "https://raw.githubusercontent.com/catppuccin/bottom/main/themes/frappe.toml"

[".config/bottom/themes/latte.toml"]
type = "file"
refreshPeriod = "168h" # 1-wee
url = "https://raw.githubusercontent.com/catppuccin/bottom/main/themes/latte.toml"

[".config/bottom/themes/macchiato.toml"]
type = "file"
refreshPeriod = "168h" # 1-wee
url = "https://raw.githubusercontent.com/catppuccin/bottom/main/themes/macchiato.toml"

[".config/bottom/themes/mocha.toml"]
type = "file"
refreshPeriod = "168h" # 1-wee
url = "https://raw.githubusercontent.com/catppuccin/bottom/main/themes/mocha.toml"

{{ if eq .chezmoi.os "darwin" }}

[".config/kitty/themes"]
type = "archive"
refreshPeriod = "168h" # 1-week
stripComponents = 2
include = ["*/themes/*.conf"]
url = "https://github.com/catppuccin/kitty/archive/refs/heads/main.zip"

["Library/Developer/Xcode/UserData/FontAndColorThemes"]
type = "archive"
refreshPeriod = "168h" # 1-week
stripComponents = 2
include = ["*/dist/*.xccolortheme"]
url = "https://github.com/catppuccin/xcode/archive/refs/heads/main.zip"

{{ end }}

{{ if eq .chezmoi.os "windows" }}

["Tools/FaithType"]
type = "archive"
refreshPeriod = "168h" # 1-week
stripComponents = 1
url = "https://github.com/m13253/FaithType/releases/download/latest/FaithType.zip"

["Tools/Disable Peak Limiter"]
type = "archive"
stripComponents = 1
url = "https://kawamoto.no-ip.org/henteko/myapp/dpeaklim12.zip"

["Tools/noMeiryoUI"]
type = "archive"
url = "https://github.com/Tatsu-syo/noMeiryoUI/releases/download/TAG-3.2.1.1/noMeiryoUI3.2.1.1.zip"

["Documents/PowerShell/Scripts/Complete-Xh.ps1"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://raw.githubusercontent.com/ducaale/xh/master/completions/_xh.ps1"

["Documents/PowerShell/Modules/Catppuccin"]
type = "archive"
exact = true
refreshPeriod = "168h" # 1-week
stripComponents = 1
include = ["*/en-US/**", "*/*.ps*"]
url = "https://github.com/catppuccin/powershell/archive/refs/heads/main.zip"

["AppData/Local/imhex/themes/catppuccin-frappe.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://github.com/catppuccin/imhex/releases/latest/download/catppuccin-frappe.json"
["AppData/Local/imhex/themes/catppuccin-latte.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://github.com/catppuccin/imhex/releases/latest/download/catppuccin-latte.json"
["AppData/Local/imhex/themes/catppuccin-macchiato.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://github.com/catppuccin/imhex/releases/latest/download/catppuccin-macchiato.json"
["AppData/Local/imhex/themes/catppuccin-mocha.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://github.com/catppuccin/imhex/releases/latest/download/catppuccin-mocha.json"

["AppData/Local/clink/lib/clink-zoxide"]
type = "archive"
exact = true
refreshPeriod = "168h" # 1-week
stripComponents = 1
url = "https://github.com/shunsambongi/clink-zoxide/archive/refs/heads/master.zip"

{{ else }} # Non-Windows

{{   if lookPath "base64" }}

[".local/bin/copy"]
type = "file"
refreshPeriod = "168h" # 1-wee
url = "https://raw.githubusercontent.com/xPMo/OSC-52/main/bash/copy"
executable = true

{{     if false }}
# Windows Terminal は paste はサポートしていない模様
# https://github.com/microsoft/terminal/issues/9479
[".local/bin/paste"]
type = "file"
refreshPeriod = "168h" # 1-wee
url = "https://raw.githubusercontent.com/xPMo/OSC-52/main/bash/paste"
executable = true
{{     end}}

{{   end }}

[".config/fish"]
type = "archive"
refreshPeriod = "168h" # 1-week
stripComponents = 1
include = ["*/completions/*.fish", "*/functions/*.fish"]
url = "https://github.com/jorgebucaran/fisher/archive/refs/heads/main.zip"

{{   if lookPath "docker" }}
[".config/fish/completions/docker.fish"]
type = "file"
refreshPeriod = "168h" # 1-week
{{ $dockerVersion := output "docker" "--version" | splitList "," | first | splitList " " | last }}
url = {{ printf "https://raw.githubusercontent.com/docker/cli/v%s/contrib/completion/fish/docker.fish" $dockerVersion | quote }}
{{   end }}

[".config/kak/bundle/kak-bundle"]
type = "archive"
exact = true
refreshPeriod = "168h" # 1-week
stripComponents = 1
include = ["*/README.md", "*/rc/**"]
url = "https://github.com/jdugan6240/kak-bundle/archive/refs/heads/master.zip"

{{ end }}

# SchemaStore Cache

[".cache/schemastore/catalog.json"]
type = "file"
refreshPeriod = "168h"
url = "https://www.schemastore.org/api/json/catalog.json"

# GitHub commit cache

[".cache/chezmoi-commits/helix-editor.json"]
type = "file"
refreshPeriod = "24h" # 1-day
url = "https://api.github.com/repos/helix-editor/helix/commits/master"

{{ if eq .chezmoi.os "windows" }}

[".cache/chezmoi-commits/buffer-language-server.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://api.github.com/repos/metafates/buffer-language-server/commits/main"

[".cache/chezmoi-commits/simple-completion-language-server.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://api.github.com/repos/estin/simple-completion-language-server/commits/main"

{{ end }}

# GitHub release cache

{{ if eq .chezmoi.os "windows" }}
[".cache/chezmoi-releases/efm-langserver.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://api.github.com/repos/mattn/efm-langserver/releases/latest"
{{ end }}

[".cache/chezmoi-releases/golangci-lint-langserver.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://api.github.com/repos/nametake/golangci-lint-langserver/releases/latest"

[".cache/chezmoi-releases/golangci-lint.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://api.github.com/repos/golangci/golangci-lint/releases/latest"

[".cache/chezmoi-releases/tailwindcss-intellisense.json"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://api.github.com/repos/tailwindlabs/tailwindcss-intellisense/releases/latest"

