# https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/
#
# > .chezmoiexternal.$FORMAT is interpreted as a template.
# > This allows different externals to be included on different machines.

[".vim/pack/chezmoi/opt/minpac"]
type = "archive"
exact = true
include = ["*/autoload/**", "*/doc/**", "*/plugin/**"]
refreshPeriod = "24h"
stripComponents = 1
url = "https://github.com/k-takata/minpac/archive/refs/heads/master.zip"

[".vim/colors/zenesque.vim"]
type = "file"
url = "https://raw.githubusercontent.com/vim-scripts/zenesque.vim/master/colors/zenesque.vim"

[".local/share/dict/"]
type = "archive"
url = "https://sourceforge.net/projects/wordlist/files/speller/2020.12.07/wordlist-en_US-2020.12.07.zip/download"
include = ["en_US.txt"]

{{ if eq .chezmoi.os "windows" }}
["Documents/PowerShell/Modules/Catppuccin"]
type = "archive"
refreshPeriod = "168h" # 1-week
extract = true
stripComponents = 1
include = ["*/en-US/**", "*/*.ps*"]
url = "https://github.com/catppuccin/powershell/archive/refs/heads/main.zip"

[".local/bin/eza.exe"]
type = "file"
refreshPeriod = "168h" # 1-week
url = "https://github.com/eza-community/eza/releases/latest/download/x86_64-pc-windows-gnu-eza.exe"
{{ end }}

{{ if ne .chezmoi.os "windows" }}
[".config/kak/bundle/kak-bundle"]
type = "archive"
refreshPeriod = "168h" # 1-week
extract = true
stripComponents = 1
include = ["*/README.md", "*/rc/**"]
url = "https://github.com/jdugan6240/kak-bundle/archive/refs/heads/master.zip"
{{ end }}
