[general]
live_config_reload = true
import = [
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

[env]
ALACRITTY = "1"

[window]
dimensions = { columns = 136, lines = 40 }
padding = { x = 8, y = 8 }

[font]
normal = { family = "PlemolJP Console NF", style = "Regular" }
bold = { family = "PlemolJP Console NF", style = "SemiBold" }
italic = { family = "PlemolJP Console NF", style = "Italic" }
bold_italic = { family = "PlemolJP Console NF", style = "SemiBold Italic" }
size = 14.0

[bell]
animation = "EaseOutExpo"
duration = 100

[selection]
save_to_clipboard = true

[terminal]
shell = { args = ["~"], program = "wsl" }

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"
