[bell]
animation = "EaseOutExpo"

[font]
builtin_box_drawing = true
size = 12.0

[font.bold]
family = "PlemolJP Console NF"
style = "Bold"

[font.bold_italic]
family = "PlemolJP Console NF"
style = "Bold Italic"

[font.italic]
family = "PlemolJP Console NF"
style = "Italic"

[font.normal]
family = "PlemolJP Console NF"
style = "Regular"

[shell]
args = ["-Login"]
program = "pwsh"

[window]
opacity = 0.92

[window.dimensions]
columns = 136
lines = 40

[window.padding]
x = 8
y = 8
