[general]
live_config_reload = true

[env]
ALACRITTY = "1"

[window]
dimensions = { columns = 136, lines = 40 }
opacity = 0.92
dynamic_padding = true
padding = { x = 8, y = 8 }

[font]
normal = { family = "PlemolJP Console NF", style = "Regular" }
bold = { family = "PlemolJP Console NF", style = "Bold" }
italic = { family = "PlemolJP Console NF", style = "Italic" }
bold_italic = { family = "PlemolJP Console NF", style = "Bold Italic" }
size = 13.0
offset = { x = 0, y = 1 }
builtin_box_drawing = true

[bell]
animation = "EaseOutExpo"
duration = 100

[selection]
save_to_clipboard = true

[terminal]

[terminal.shell]
args = ["-Login"]
program = "pwsh"

[mouse]
hide_when_typing = true
