[bell]
animation = "EaseOutExpo"
duration = 100

[env]
ALACRITTY = "1"

[font]
builtin_box_drawing = true
size = 12.0

normal = { family = "PlemolJP Console NF", style = "Regular" }
bold = { family = "PlemolJP Console NF", style = "Bold" }
italic = { family = "PlemolJP Console NF", style = "Italic" }
bold_italic = { family = "PlemolJP Console NF", style = "Bold Italic" }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["-Login"]
program = "pwsh"

[window]
dimensions = { columns = 136, lines = 40 }
opacity = 0.92
dynamic_padding = true
padding = { x = 8, y = 8 }

[terminal]
