$BaseDir = Join-Path (Get-Content Env:USERPROFILE) ".config" "bottom"

$Header = @"
# This file is generated by the script run_after_concat_config.ps1
# Concat default config with theme config
#

"@

$Header | Out-File -FilePath .\bottom.toml

Get-Content -Path (Join-Path $BaseDir "default_config.toml") | Out-File -FilePath .\bottom.toml -Append

Write-Output "# Macchiato Theme" | Out-File -FilePath .\bottom.toml -Append
Get-Content -Path (Join-Path $BaseDir "themes" "macchiato.toml") | Out-File -FilePath .\bottom.toml -Append

