#!/bin/sh
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -e
PATH="/usr/local/bin:$PATH"
# trap "rm -f .git/tags.$$" EXIT
# git ls-files | ctags --tag-relative -f.git/tags.$$ --exclude=.git -L -
# mv .git/tags.$$ .git/tags
cd .git
trap "rm -f tags.$$" EXIT
git -C .. ls-files | sed "s@^@../@" | ctags --tag-relative=yes -ftags.$$ -L -
mv tags.$$ tags
