"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
sort_by = "natural"
linemode = "size"

[preview]
image_filer = "lanczos3"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

