[[sources]] # list of sources to load
name = "friendly-snippets"  # optional name shown on snippet description
git = "https://github.com/rafamadriz/friendly-snippets.git" # git repo with snippets collections

[[sources.paths]] # list of paths to load on current source
scope = ["python"]  # optional scopes for current snippets
path = "snippets/python/"  # where snippet file or dir located in repo

[[sources.paths]]
scope = ["dockerfile"]
path = "snippets/docker/docker_file.json"

[[sources.paths]]
scope = ["docker-compose"]
path = "snippets/docker/docker-compose.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/"

[[sources.paths]]
scope = ["bash", "zsh"]
path = "snippets/shell/"

[[sources.paths]]
scope = ["javascript", "javascriptreact"]
path = "snippets/javascript/javascript.json"

[[sources.paths]]
scope = ["javascript", "javascriptreact"]
path = "snippets/javascript/jsdoc.json"

[[sources.paths]]
scope = ["typescript", "typescriptreact"]
path = "snippets/javascript/next-ts.json"

[[sources.paths]]
scope = ["javascript", "javascriptreact"]
path = "snippets/javascript/next.json"

[[sources.paths]]
scope = ["javascript", "javascriptreact", "typescript", "typescriptreact"]
path = "snippets/javascript/react-es7.json"

[[sources.paths]]
scope = ["typescript", "typescriptreact"]
path = "snippets/javascript/react-ts.json"

[[sources.paths]]
scope = ["javascript", "javascriptreact"]
path = "snippets/javascript/react.json"

[[sources.paths]]
scope = ["typescript", "typescriptreact"]
path = "snippets/javascript/tsdoc.json"

[[sources.paths]]
scope = ["typescript", "typescriptreact"]
path = "snippets/javascript/typescript.json"

[[sources.paths]]
scope = ["hcl", "terraform"]
path = "snippets/terraform.json"

