# Default configuration: https://github.com/helix-editor/helix/blob/master/languages.toml

[language-server]

efm-langserver = { command = "efm-langserver" }
eslint-language-server = { command = "eslint-language-server", args = ["--stdio"] }
pylsp-all = { command = "pylsp-all" }
taplo-lsp = { command = "taplo-lsp", args = ["lsp", "stdio"] }
pyright-langserver = { command = "pyright-langserver", args = ["--stdio"], config = { python = { analysis = { typeCheckingMode = "strict", useLibraryCodeForTypes = true, reportMissingImports = true } } } }

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  " }
formatter = { command = "shfmt", args = ["-i", "2", "-ci"]} # Google's Style

[[language]]
name = "css"
formatter = { command = "npx", args = ["prettier", "--parser", "css"] }

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "html"
formatter = { command = "npx", args = ["prettier", "--parser", "html"] }

[[language]]
name = "json"
scope = "source.json"
formatter = { command = "npx", args = ["prettier", "--parser", "json"] }

[[language]]
name = "pwsh"
# language-id = "powershell"
scope = "source.ps1"
file-types = ["ps1", "psm1", "psd1"]
shebangs = ["pwsh"]
roots = []
comment-token = "#"
indent = { tab-width = 4, unit = "    " }

# It look broken
# https://github.com/helix-editor/helix/issues/3123
[[grammar]]
name = "pwsh"
source = { git = "https://github.com/sgur/tree-sitter-PowerShell", rev = "263b6637aa8ab4cdc8c39da3d93adb657d7aa60d" }

[[language]]
name = "jsx"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server", "eslint-language-server"]

[[language]]
name = "javascript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server", "eslint-language-server"]

[[language]]
name = "typescript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server", "eslint-language-server"]

[[language]]
name = "tsx"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server", "eslint-language-server"]

[[language]]
name = "yaml"

[[language]]
name = "toml"
language-servers = ["taplo-lsp"]

[[language]]
name = "python"
language-servers = ["pylsp-all", "pyright-langserver"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
roots = ["pyproject.toml"]
