# Suspend and Resume
define-command suspend -docstring 'suspend: backgrounds current kakoune client.' %{
    evaluate-commands %sh{
        platform=$(uname -s)
        case $platform in
            Darwin)
                kill_cmd="/bin/kill"
                break
                ;;
            Linux)
                kill_cmd="/usr/bin/kill"
                break
                ;;
        esac
        # Send kakoune client to the background
        $kill_cmd -SIGTSTP $kak_client_pid
    }
}
map global user -docstring 'suspend kakoune job' <C-z> ':suspend<ret>'

# Git integration via Tig <https://github.com/mawww/kakoune/wiki/Git-integration-via-Tig>
define-command tig -params .. -docstring "Run tig" %{
    terminal env "EDITOR=kak -c %val{session}" tig %arg{@}
}
define-command tig-blame-here -docstring "Run tig blame on the current line" %{
    tig -C %sh{git rev-parse --show-toplevel} blame -C "+%val{cursor_line}" -- %sh{
        dir="$(git rev-parse --show-toplevel)"
        printf %s "${kak_buffile##$dir/}"
    }
}

define-command tig-blame-selection -docstring "Run tig -L on the selected lines" %{
    evaluate-commands -draft -save-regs d %{
        execute-keys <a-:>
        set-register d %sh{git rev-parse --show-toplevel}
        tig -C %reg{d} %sh{
            anchor=${kak_selection_desc%,*}
            anchor_line=${anchor%.*}
            cursor=${kak_selection_desc#*,}
            cursor_line=${cursor%.*}
            d=$kak_reg_d
            printf %s "-L$anchor_line,$cursor_line:${kak_buffile##$d/}"
        }
    }
}

# https://phaazon.net/blog/more-hindsight-vim-helix-kakoune
define-command -hidden open_buffer_picker %{
    prompt buffer: -menu -buffer-completion %{
        buffer %val{text}
    }
}
map global user -docstring 'open buffer picker' b ':open_buffer_picker<ret>'

define-command -hidden open_file_picker %{
    prompt file: -menu -shell-script-candidates 'fd --type=file' %{
        edit -existing %val{text}
    }
}
map global user -docstring 'open file picker' f ':open_file_picker<ret>'

map global normal '#' :comment-line<ret>
map global normal '^' :comment-block<ret>

# ui
set-option global ui_options terminal_assistant=none terminal_enable_mouse=false

# modeline format
declare-option -docstring "name of the git branch holding the current buffer" \
    str modeline_git_branch

hook global WinCreate .* %{
    hook window NormalIdle .* %{ evaluate-commands %sh{
        branch=$(cd "$(dirname "${kak_buffile}")" && git rev-parse --abbrev-ref HEAD 2>/dev/null)
        if [ -n "${branch}" ]; then
            printf 'set window modeline_git_branch %%{%s}' "[${branch}]"
        fi
    } }
}
set-option global modelinefmt '%val{bufname} %opt{modeline_git_branch}[%opt{filetype}] %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}} - %val{client}@[%val{session}]'

# highlight
add-highlighter global/ wrap -word
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces -lf '⏎' -spc ' ' -tab '→' -nbsp '⍽' -tabpad '·'

# rc/detection/editorconfig
# make sure to install editorconfig cli (ex. brew)
hook global BufOpenFile .* %{ editorconfig-load }
hook global BufNewFile .* %{ editorconfig-load }

# rc/detection/modeline
hook global BufOpenFile .* %{ modeline-parse }

# rc/tools/grep
set-option global grepcmd 'rg --color=never --vimgrep'

# rc/tools/lint, rt/tools/format
hook global WinSetOption filetype=css %{
    set-option window lintcmd "npx --yes stylelint --formatter unix --stdin-filename='%val{buffile}'"
    set-option buffer formatcmd "npx --yes prettier --stdin-filepath=%val{buffile}"
}

hook global WinSetOption filetype=javascript %{
    set-option window lintcmd 'run() { cat "$1" |npx --yes eslint -f unix --stdin --stdin-filename "$kak_buffile";} && run'
    set-option buffer formatcmd "npx --yes prettier --stdin-filepath=%val{buffile}"
}

hook global WinSetOption filetype=json %{
    set-option window lintcmd %{ run() { cat -- "$1" | jq 2>&1 | awk -v filename="$1" '/ at line [0-9]+, column [0-9]+$/ { line=$(NF - 2); column=$NF; sub(/ at line [0-9]+, column [0-9]+$/, ""); printf "%s:%d:%d: error: %s", filename, line, column, $0; }'; } && run }
    set-option buffer formatcmd "npx --yes prettier --stdin-filepath=%val{buffile}"
}

hook global WinSetOption filetype=markdown %{
    set-option buffer formatcmd "npx --yes prettier --stdin-filepath=%val{buffile}"
}

hook global WinSetOption filetype=python %{
    set-option window lintcmd "mypy --show-column-numbers"
    set-option buffer formatcmd 'black -'
}

hook global BufSetOption filetype=rust %{
    set-option buffer formatcmd 'rustfmt'
}

hook global WinSetOption filetype=sh %{
    set-option window lintcmd "shellcheck -fgcc -Cnever"
    set-option buffer formatcmd "shfmt"
}

hook global WinSetOption filetype=yaml %{
    # set-option window lintcmd "yamllint -f parsble"
    set-option window lintcmd %{
        run() {
           # change [message-type] to message-type:
           yamllint -f parsable "$1" | sed 's/ \[\(.*\)\] / \1: /'
        } && run
    }
    set-option buffer formatcmd "npx --yes prettier --stdin-filepath=%val{buffile}"
}

# rc/tools/spell
set-option global spell_lang "en"

# bundle (installed via chezmoi)
source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"

# bundle/auto-pairs
bundle auto-pairs.kak https://github.com/alexherbo2/auto-pairs.kak %{
    enable-auto-pairs
}

# bundle/catppuccin
bundle-noload catppuccin 'git clone https://github.com/catppuccin/kakoune catppuccin' %{
} %{
    mkdir -p ${kak_config}/colors
    ln -sfn "${kak_opt_bundle_path}/catppuccin/colors" "${kak_config}/colors/catppuccin"
}
try %{
    colorscheme catppuccin_macchiato
}

# bundle/kak-lsp
bundle kak-lsp https://github.com/kak-lsp/kak-lsp %{
    # eval %sh{kak-lsp --kakoune --session $kak_session}
    set global lsp_cmd "kak-lsp -s %val{session} -vvv --log ~/.cache/kak-lsp/kak-lsp.log"

    set-option global lsp_hover_anchor true
    set-option global lsp_auto_show_code_actions true
    set-option global lsp_diagnostic_line_error_sign 'E'
    set-option global lsp_diagnostic_line_hint_sign 'H'
    set-option global lsp_diagnostic_line_info_sign 'I'
    set-option global lsp_diagnostic_line_warning_sign 'W'

    lsp-enable
    lsp-auto-hover-enable
    lsp-inlay-hints-enable global
    lsp-inlay-diagnostics-enable global

    map global user -docstring 'lsp mode' l ':enter-user-mode lsp<ret>'
} %{
    cargo install --locked --force --path .
}

# bundle/kak-tree-sitter
bundle kak-tree-sitter https://github.com/phaazon/kak-tree-sitter %{
    eval %sh{ kak-tree-sitter --kakoune --daemonize --server --session $kak_session }
} %{
    (
        cd kak-tree-sitter
        cargo install --locked --force --path .
    )
    (
        cd ktsctl
        cargo install --locked --force --path .
    )
    # fetch -> compile -> install: KDL syntax
    ktscl --fetch --compile --install kdl
    ktscl --fetch --compile --install nu
    ktscl --fetch --compile --install sshclientconfig
    ktscl --fetch --compile --install xml
}
