# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/vscode-markdownlint/main/markdownlint-cli2-config-schema.json
---
config:
  default: true
  # MD013/line-length
  MD013: false
  # MD025/single-title/single-h1
  MD025: false
  # MD033/no-inline-html
  MD033: false
  # MD041/first-line-heading/first-line-h1
  MD041: false
  # MD051/link-fragments
  MD051: false
  # MD053/link-image-reference-definitions
  MD053: false

noProgress: true
