---
version: "0.2"
language: en
allowCompoundWords: true
dictionaries:
  - user-words
  - local-words
dictionaryDefinitions:
  - addWords: true
    name: user-words
    path: ~/.config/user-words.txt
  - addWords: true
    name: local-words
    path: ~/.config/local-words.txt
overrides:
  - filename: "**/{*.vim,vimrc,gvimrc}"
    languageId: "viml"
languageSettings:
  - languageId: "viml"
    locale: "*"
    dictionaries: ["viml"]
    dictionaryDefinitions:
      - addWords: true
        name: viml
        path: ~/.config/viml-words.txt
ignorePaths:
  - 'node_modules/**'
