$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
allowCompoundWords: true
dictionaries:
  - user-words
dictionaryDefinitions:
  - addWords: true
    name: user-words
    path: ~/.config/user-words.txt
ignorePaths:
  - node_modules

