# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
---
version: "0.2"
language: en
allowCompoundWords: true
dictionaries:
  - user-words
  - local-words
dictionaryDefinitions:
  - addWords: true
    name: user-words
    path: ~/.config/user-words.txt
  - addWords: true
    name: local-words
    path: ~/.config/local-words.txt
overrides:
  - filename: "**/{*.vim,vimrc,gvimrc}"
    languageId: "vim"
languageSettings:
  - languageId: "vim"
    locale: "*"
    dictionaries: ["vim"]
    dictionaryDefinitions:
      - addWords: true
        name: vim
        path: ~/.config/vim-words.txt
  - languageId: "python"
    locale: "*"
    dictionaries: ["python"]
    dictionaryDefinitions:
      - addWords: true
        name: python
        path: ~/.config/python-words.txt
  - languageId: "go"
    locale: "*"
    dictionaries: ["go"]
    dictionaryDefinitions:
      - addWords: true
        name: go
        path: ~/.config/go-words.txt
ignorePaths:
  - 'node_modules/**'
